-- AlterTable
ALTER TABLE "Booking" ADD COLUMN "age" INTEGER NOT NULL DEFAULT 18;
ALTER TABLE "Booking" ADD COLUMN "gender" TEXT NOT NULL DEFAULT 'prefer_not_to_say';
ALTER TABLE "Booking" ADD COLUMN "termsAccepted" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Booking" ALTER COLUMN "age" DROP DEFAULT;
ALTER TABLE "Booking" ALTER COLUMN "gender" DROP DEFAULT;
